/**
 * JARVIS Engineering Validation — real physics & EE knowledge for Build Studio.
 *
 * Takes the CAD model (geometry, material) plus the hardware analysis
 * (components, power requirements) and runs quantitative checks a maker or
 * engineer would run before building something real:
 *
 *   1. Structural  — self-weight beam bending → stress, safety factor
 *   2. Thermal     — enclosure heat dissipation vs. component power draw
 *   3. Electrical  — rail current totals, regulator headroom, wire sizing
 *   4. Battery     — runtime estimate at average draw
 *   5. Print/Build — wall thickness, tolerance, material fit notes
 *
 * Every number is traceable: checks carry the formula used so the UI can
 * explain WHY a warning fires. Formulas are classic first-order engineering
 * estimates (Shigley's, standard electronics practice) — good enough to
 * catch bad designs early, not a replacement for FEA/SPICE.
 */

import type { CADModel, MaterialId } from './cad';
import { MATERIALS, modelStats } from './cad';

// ═══════════════════════════════════════════════════════════════
// Material mechanical/thermal properties (typical room-temp values)
// ═══════════════════════════════════════════════════════════════

export interface MaterialMech {
  /** ultimate tensile strength, MPa */
  uts: number;
  /** Young's modulus, GPa */
  E: number;
  /** max continuous service temp, °C */
  tMax: number;
  /** thermal conductivity, W/m·K */
  k: number;
  /** for metals: true; for plastics: creep-prone */
  rigid: boolean;
}

export const MATERIAL_MECH: Record<MaterialId, MaterialMech> = {
  pla:           { uts: 60,  E: 3.5, tMax: 50,  k: 0.13, rigid: false },
  abs:           { uts: 40,  E: 2.3, tMax: 80,  k: 0.17, rigid: false },
  petg:          { uts: 53,  E: 2.1, tMax: 70,  k: 0.2,  rigid: false },
  resin:         { uts: 45,  E: 2.8, tMax: 60,  k: 0.18, rigid: false },
  aluminium:     { uts: 310, E: 69,  tMax: 150, k: 167,  rigid: true },
  steel:         { uts: 505, E: 193, tMax: 400, k: 16,   rigid: true },
  titanium:      { uts: 950, E: 114, tMax: 400, k: 6.7,  rigid: true },
  carbon_fiber:  { uts: 600, E: 70,  tMax: 120, k: 5,    rigid: true },
};

// Typical component thermal footprint (W of heat) by keyword — used when the
// hardware analysis gives voltage/current but not a heat split.
const HEAT_HINTS: Array<[RegExp, number]> = [
  [/motor|servo|stepper/i, 0.85],   // 85% of electrical power becomes heat under load
  [/regulator|buck|ldo/i, 0.4],
  [/esp32|esp8266/i, 0.5],
  [/raspberry|pi 4|pi 5/i, 4.5],    // watts, typical load
  [/arduino/i, 0.25],
  [/neo ?pixel|led strip|ws2812/i, 0.06], // per LED — caller multiplies by count
  [/relay/i, 0.7],
  [/gps/i, 0.35],
  [/camera/i, 0.8],
];

/**
 * Parse a current spec into amps. Handles the hardware engine's range
 * format ("80-240mA" → 0.24, taking the worst case), plain amps ("3"),
 * explicit units ("500mA", "1.5A"), and non-values ("N/A" → 0).
 */
export function parseCurrentAmps(spec: string): number {
  if (!spec) return 0;
  const s = spec.trim().toLowerCase();
  if (s === 'n/a' || s === 'unknown' || s === '-') return 0;
  // Range "80-240ma" or "0.1-5ma": worst-case upper bound
  const range = s.match(/^([\d.]+)\s*-\s*([\d.]+)\s*(ma|a)?$/);
  if (range) {
    const hi = parseFloat(range[2]);
    return range[3] === 'ma' ? hi / 1000 : hi;
  }
  // Unit-suffixed "500ma" / "1.5a"
  const unit = s.match(/^([\d.]+)\s*(ma|a)$/);
  if (unit) return unit[2] === 'ma' ? parseFloat(unit[1]) / 1000 : parseFloat(unit[1]);
  // Bare number: assume amps
  const bare = parseFloat(s);
  return Number.isFinite(bare) ? bare : 0;
}

/** Estimate total heat (W) generated by a list of power requirements. */
export function estimateHeat(powers: Array<{ component: string; voltage: string; current: string }>): number {
  let total = 0;
  for (const p of powers) {
    const v = parseFloat(p.voltage) || 0;
    const a = parseCurrentAmps(p.current);
    const w = v * a;
    let frac = 0.5; // default: half the power becomes heat
    for (const [re, f] of HEAT_HINTS) {
      if (re.test(p.component)) { frac = typeof f === 'number' && f <= 1 ? f : 0.5; break; }
    }
    // Raspberry Pi hint is absolute watts, not a fraction
    if (/raspberry|pi 4|pi 5/i.test(p.component)) { total += 4.5; continue; }
    total += w * frac;
  }
  return total;
}

// ═══════════════════════════════════════════════════════════════
// Check types
// ═══════════════════════════════════════════════════════════════

export type CheckStatus = 'pass' | 'warn' | 'fail';

export interface Check {
  id: string;
  domain: 'structural' | 'thermal' | 'electrical' | 'battery' | 'print';
  title: string;
  status: CheckStatus;
  value: string;
  detail: string;
  formula?: string;
}

export interface ValidationReport {
  checks: Check[];
  summary: { pass: number; warn: number; fail: number };
  headline: string;
}

// ═══════════════════════════════════════════════════════════════
// Structural: simply-supported beam under self-weight
// ═══════════════════════════════════════════════════════════════

function structuralCheck(model: CADModel): Check {
  const mech = MATERIAL_MECH[model.material];
  const stats = modelStats(model);
  const massKg = stats.massG / 1000;
  // Longest span of the bbox, in meters
  const L = Math.max(stats.boundingBoxMm.x, stats.boundingBoxMm.y, stats.boundingBoxMm.z) / 1000;
  // Model the part as a rectangular section b × h spanning L (bbox cross-section)
  const dims = [stats.boundingBoxMm.x, stats.boundingBoxMm.y, stats.boundingBoxMm.z].sort((a, b) => a - b);
  const b = dims[0] / 1000; // m
  const h = dims[1] / 1000; // m
  const sectionModulus = (b * h * h) / 6; // m³
  const w = massKg * 9.81 / L; // distributed load N/m
  const sigma = (w * L * L) / (8 * sectionModulus) / 1e6; // MPa
  const fos = sigma > 0 ? mech.uts / sigma : Infinity;
  const status: CheckStatus = fos >= 4 ? 'pass' : fos >= 1.8 ? 'warn' : 'fail';
  return {
    id: 'structure',
    domain: 'structural',
    title: 'Self-weight bending',
    status,
    value: `SF ${fos >= 100 ? '100+' : fos.toFixed(1)}`,
    detail: fos >= 1.8
      ? `Peak bending stress ${sigma.toFixed(2)} MPa vs ${mech.uts} MPa UTS. Holds its own weight with margin.`
      : `Peak stress ${sigma.toFixed(1)} MPa vs ${mech.uts} MPa UTS — the part may sag or crack under its own weight across ${L.toFixed(2)} m. Add ribs, reduce span, or switch material.`,
    formula: 'σ = wL²/8Z · SF = UTS/σ (simply supported, self-weight)',
  };
}

// ═══════════════════════════════════════════════════════════════
// Thermal: enclosure dissipation vs internal heat
// ═══════════════════════════════════════════════════════════════

function thermalCheck(model: CADModel, heatW: number): Check {
  const mat = MATERIAL_MECH[model.material];
  const stats = modelStats(model);
  const bb = stats.boundingBoxMm;
  // Exterior surface area of the bbox (m²) — the radiator
  const area = 2 * (bb.x * bb.y + bb.y * bb.z + bb.x * bb.z) / 1e6;
  // Natural convection+radiation: h ≈ 6–10 W/m²K. Use 8. Allow 20K rise.
  const h = 8;
  const dtAllowed = 20;
  const dissipation = h * area * dtAllowed; // W
  const status: CheckStatus = heatW <= dissipation * 0.6 ? 'pass'
    : heatW <= dissipation ? 'warn' : 'fail';
  const rise = area > 0 ? heatW / (h * area) : Infinity;
  return {
    id: 'thermal',
    domain: 'thermal',
    title: 'Thermal dissipation',
    status,
    value: `ΔT ≈ ${rise > 999 ? '999' : rise.toFixed(0)}°C`,
    detail: status === 'pass'
      ? `${heatW.toFixed(1)} W of heat over ${(area * 1e4).toFixed(0)} cm² sheds at roughly ${rise.toFixed(0)}°C above ambient — comfortable for ${mat.rigid ? 'this material' : MATERIALS[model.material].label} and the electronics.`
      : status === 'warn'
        ? `${heatW.toFixed(1)} W of heat warms the case ~${rise.toFixed(0)}°C above ambient. ${mat.tMax <= 60 ? MATERIALS[model.material].label + ' softens near ' + mat.tMax + '°C — ' : ''}Consider vents, a metal shell, or a heatsink.`
        : `${heatW.toFixed(1)} W cannot escape through ${(area * 1e4).toFixed(0)} cm² naturally (~${rise.toFixed(0)}°C rise). Components will throttle or fail: add vents/fan, or move to aluminium.`,
    formula: 'ΔT = Q/(h·A), h = 8 W/m²K natural convection, allowed rise 20°C',
  };
}

// ═══════════════════════════════════════════════════════════════
// Electrical: current totals, wire gauge, regulator headroom
// ═══════════════════════════════════════════════════════════════

export interface PowerRow { component: string; voltage: string; current: string; source: string }

function electricalCheck(powers: PowerRow[]): Check {
  // Group by rail voltage
  const rails = new Map<number, number>();
  for (const p of powers) {
    const v = Math.round(parseFloat(p.voltage) || 0);
    const a = parseCurrentAmps(p.current);
    rails.set(v, (rails.get(v) ?? 0) + a);
  }
  interface Rail { v: number; a: number }
  let worst: Rail | null = null;
  rails.forEach((amps, volts) => {
    if (!worst || amps > worst.a) worst = { v: volts, a: amps };
  });
  const worstRail = worst as Rail | null;
  const a = worstRail ? worstRail.a : 0;
  // 28 AWG jumper ≈ 0.9 A continuous, 22 AWG ≈ 3 A, 18 AWG ≈ 7 A
  const wire = a <= 0.9 ? '28–26 AWG jumpers are fine' : a <= 3 ? 'use 22 AWG or thicker' : a <= 7 ? 'use 18 AWG or thicker' : 'split across rails — this exceeds typical breadboard wiring';
  const status: CheckStatus = a <= 3 ? 'pass' : a <= 7 ? 'warn' : 'fail';
  const railList = [...rails.entries()].map(([v, i]) => `${v}V@${i.toFixed(2)}A`).join(' · ') || 'none';
  return {
    id: 'electrical',
    domain: 'electrical',
    title: 'Power rail budget',
    status,
    value: `${a.toFixed(2)} A peak`,
    detail: `Rails: ${railList}. On the busiest rail, ${wire}. USB delivers 0.5 A (2.0 A on good ports) — a bench supply or dedicated regulator is needed above that.`,
    formula: 'ΣI per rail vs 0.5 A USB / 3 A 22AWG / 7 A 18AWG limits',
  };
}

// ═══════════════════════════════════════════════════════════════
// Battery runtime
// ═══════════════════════════════════════════════════════════════

function batteryCheck(powers: PowerRow[]): Check {
  const totalW = powers.reduce((s, p) => s + (parseFloat(p.voltage) || 0) * parseCurrentAmps(p.current), 0);
  // Typical 18650 / LiPo pack in a maker project: 3.7V 2500mAh ≈ 9.25 Wh
  const packWh = 9.25;
  const hours = totalW > 0 ? packWh / totalW : Infinity;
  const status: CheckStatus = hours >= 4 ? 'pass' : hours >= 1 ? 'warn' : 'fail';
  const hTxt = hours === Infinity ? 'no load' : hours >= 1 ? `${hours.toFixed(1)} h` : `${(hours * 60).toFixed(0)} min`;
  return {
    id: 'battery',
    domain: 'battery',
    title: 'Battery runtime',
    status,
    value: hTxt,
    detail: status === 'fail'
      ? `At ${(totalW).toFixed(1)} W average draw, a common 9 Wh pack dies in ${hTxt}. Use a bigger pack, duty-cycling, or wall power.`
      : `At ${(totalW).toFixed(1)} W average draw, a standard 3.7 V 2500 mAh pack (9.25 Wh) runs ${hTxt}. Scale the pack linearly for longer runtime.`,
    formula: 'runtime = packWh / Σ(V·I) · reference pack 3.7V 2500mAh',
  };
}

// ═══════════════════════════════════════════════════════════════
// Print / build manufacturability
// ═══════════════════════════════════════════════════════════════

function printCheck(model: CADModel): Check {
  const stats = modelStats(model);
  const minDim = Math.min(stats.boundingBoxMm.x, stats.boundingBoxMm.y, stats.boundingBoxMm.z);
  const walls = model.shapes.filter(s => s.kind === 'shell').map(s => s.params.wall ?? 3);
  const minWall = walls.length ? Math.min(...walls) : null;
  const ok = stats.printability.ok && (minWall === null || minWall >= 1.2);
  const status: CheckStatus = ok ? 'pass' : minWall !== null && minWall < 0.8 ? 'fail' : 'warn';
  const notes: string[] = [];
  if (minWall !== null && minWall < 1.2) notes.push(`${minWall} mm wall < the 1.2 mm FDM minimum — print will leak or delaminate.`);
  if (!stats.printability.ok) notes.push(stats.printability.notes.join(' '));
  if (stats.boundingBoxMm.x > 220 || stats.boundingBoxMm.y > 220 || stats.boundingBoxMm.z > 250) notes.push('Exceeds a 220×220×250 mm print bed — split the part or outsource.');
  return {
    id: 'print',
    domain: 'print',
    title: 'Manufacturability',
    status,
    value: `${stats.volumeCm3.toFixed(0)} cm³ · ${stats.massG.toFixed(0)} g`,
    detail: notes.length ? notes.join(' ') : `Fits a consumer print bed, minimum feature ${minDim.toFixed(1)} mm, ${stats.triangles.toLocaleString()} triangles. ${MATERIALS[model.material].label} at ${stats.volumeCm3.toFixed(0)} cm³ ≈ ${stats.massG.toFixed(0)} g (${(stats.massG / 1000 * 20).toFixed(1)} m of 1.75 mm filament).`,
    formula: 'FDM rules: ≥1.2 mm walls, ≥2 mm features, bed ≤220×220×250 mm',
  };
}

// ═══════════════════════════════════════════════════════════════
// Public API
// ═══════════════════════════════════════════════════════════════

export interface BuildValidationInput {
  model: CADModel;
  powers?: PowerRow[];
}

export function validateBuild({ model, powers = [] }: BuildValidationInput): ValidationReport {
  const checks: Check[] = [];
  const heat = estimateHeat(powers);
  const hasPower = powers.length > 0;

  checks.push(structuralCheck(model));
  checks.push(thermalCheck(model, heat));
  if (hasPower) {
    checks.push(electricalCheck(powers));
    checks.push(batteryCheck(powers));
  }
  checks.push(printCheck(model));

  const summary = {
    pass: checks.filter(c => c.status === 'pass').length,
    warn: checks.filter(c => c.status === 'warn').length,
    fail: checks.filter(c => c.status === 'fail').length,
  };
  const headline = summary.fail > 0
    ? `${summary.fail} blocking issue${summary.fail > 1 ? 's' : ''} before this can be built`
    : summary.warn > 0
      ? `Buildable, with ${summary.warn} thing${summary.warn > 1 ? 's' : ''} to watch`
      : 'All engineering checks pass — ready to build';
  return { checks, summary, headline };
}

/** Material recommendation heuristic: heat + stiffness needs push metal. */
export function recommendMaterial(heatW: number, spanMm: number): { id: MaterialId; why: string } {
  if (heatW > 8) return { id: 'aluminium', why: `${heatW.toFixed(0)} W of heat — aluminium's 167 W/mK conductivity acts as the heatsink.` };
  if (spanMm > 300) return { id: 'carbon_fiber', why: `${(spanMm / 1000).toFixed(1)} m span — carbon fiber's 600 MPa UTS keeps it stiff without mass.` };
  return { id: 'petg', why: 'Balanced strength, temperature resistance to 70°C, and easy printing.' };
}
